name: flutter_linkedin_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/app_logo_svg.svg
    - assets/bg_image_1.jpeg
    - assets/bg_image_2.png
    - assets/bg_image_3.jpeg
    - assets/celebrate.png
    - assets/curious.png
    - assets/google_logo_svg.svg
    - assets/insightful.png
    - assets/linkedin_loading.gif
    - assets/linkedin_word_logo.png
    - assets/love.png
    - assets/on_boarding_1.jpg
    - assets/on_boarding_2.jpg
    - assets/on_boarding_3.jpg
    - assets/post_image_1.jpg
    - assets/post_image_2.jpg
    - assets/post_image_3.jpg
    - assets/post_image_4.jpg
    - assets/post_image_5.jpg
    - assets/profile_1.jpeg
    - assets/profile_2.jpeg
    - assets/thumbs_up.png